### ISSUE TITLE
Missing `ConnectionFactoryProvider`

### ISSUE THREAD

**Issue by mp911de** [ibmdb/java_reactive_driver#5]
As per [§4.3 R2DBC SPI Compliance](https://r2dbc.io/spec/1.0.0.RELEASE/spec/html/#compliance.r2dbc), the ServiceLoader-based `ConnectionFactoryProvider` is missing. This lookup enables creating a `ConnectionFactory` from an R2DBC URL such as `ConnectionFactories.get("r2dbc:postgres://[<username>:<password>@]<host>:<port>/<database>")`, see `ConnectionFactoryOptions` for reference.

**Comment by rs-rappavu** [comment]
Yes, this class is not available yet. Will be adding it.

**Comment by adrinerandrade** [comment]
Hello everyone!

Please, if implemented can you provide support for uri where the current schema can be defined? For example, we have some Spring applications here where the connections as defined in such way:

```yaml
datasource:
  db2:
    url: jdbc:db2://<host>:<port>/<database>:currentSchema=<schemaName>;
    username: <user>
    password: <password>
```

It works perfectly. In the builder I could not find a schema configuration, and was not clear to me where I could configure it. This approach is better then to set schema for every connection provided.
